services:
  database:
    image: 'postgres:16.3'

    ports:
      - 5432:5432

    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: loafmap_db
    
    volumes:
      # - ./postgresql/data:/var/lib/postgresql/data:rw
      - ./postgresql/sql:/docker-entrypoint-initdb.d:ro

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.8
  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    
    ports:
      - 15432:80
    
    depends_on:
      - database
    
    restart: unless-stopped

secrets:
  POSTGRES_USER:
    file: ./.secrets/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./.secrets/POSTGRES_PASSWORD
 